---
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: myshipyard
spec:
  stages:
    - name: stage1
      sequences:
        - name: evaluation
          tasks:
          - name: evaluation